In [ ]:
import pandas as pd
import random
 
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame(lst, columns={'whoAmI'})
data.head()

  whoAmI
0  robot
1  human
2  human
3  robot
4  robot

In [ ]:
one_hot = pd.DataFrame(index=range(0, len(lst)), columns=['whoAmI_human', 'whoAmI_robot'])
for index, row in one_hot.iterrows():
  if lst[index] == 'human':
    row['whoAmI_human'] = 1
    row['whoAmI_robot'] = 0
  else:
    row['whoAmI_human'] = 0
    row['whoAmI_robot'] = 1

one_hot.head()

  whoAmI_human whoAmI_robot
0            0            1
1            1            0
2            1            0
3            0            1
4            0            1